//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCB_TKMIDIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PROT_ANALISE
    {
        public System.DateTime BIL_DIA_CIN { get; set; }
        public string SAL_CD_ANCINE { get; set; }
        public string BIL_PROT { get; set; }
    }
}
